# Generated by Django 4.2.1 on 2023-06-10 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_comments_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
