# Generated by Django 4.2.1 on 2023-06-10 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_comment_created_at_comment_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='updated_at',
        ),
    ]
