# Generated by Django 4.2.1 on 2023-06-10 14:33

from django.db import migrations, models
import django.utils.timezone
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_comment_created_at_remove_comment_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now=True,default=django.utils.timezone.now().isoformat()),
        ),
        migrations.AddField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now().isoformat()),
            # field=models.DateTimeField(auto_now_add=True, default=datetime.datetime.now().isoformat()),
            preserve_default=False,
        ),
    ]
